#!/bin/bash
# capdb-python-build-env.sh — Emit build environment for Python ctypes with CapDB
#
# Usage:
#   source ./capdb-python-build-env.sh /path/to/capdb/build
#   python -m pytest

set -e

if [ $# -ne 1 ]; then
    echo "Usage: $0 <capdb-build-dir>" >&2
    echo "" >&2
    echo "Example:" >&2
    echo "  source $0 ../CapDB/build" >&2
    echo "  python -m pytest" >&2
    exit 1
fi

CAPDB_BUILD="$(cd "$1" && pwd)"
CAPDB_CLIENT="$(cd "$(dirname "$CAPDB_BUILD")/capdb/client" && pwd)"
CAPDB_GENERATED="$CAPDB_BUILD/generated"

if [ ! -d "$CAPDB_BUILD" ]; then
    echo "Error: $CAPDB_BUILD does not exist" >&2
    exit 1
fi

if [ ! -f "$CAPDB_BUILD/libcapdb.so" ] && [ ! -f "$CAPDB_BUILD/libcapdb.dylib" ] && [ ! -f "$CAPDB_BUILD/capdb.dll" ]; then
    echo "Error: loadable libcapdb not found in $CAPDB_BUILD" >&2
    echo "Run: cd $CAPDB_BUILD && cmake .. && make" >&2
    exit 1
fi

# Generate a Python module with the paths
cat > capdb_build_env.py <<EOF
# Auto-generated by capdb-python-build-env.sh
CAPDB_BUILD_DIR = "$CAPDB_BUILD"
CAPDB_LIBRARY = "$CAPDB_BUILD/libcapdb.so"
CAPDB_CLIENT_LIBRARY = "$CAPDB_BUILD/libcapdb.so"
CAPDB_INCLUDE_DIR = "$CAPDB_CLIENT"
CAPDB_GENERATED_DIR = "$CAPDB_GENERATED"
CAPDB_LIBRARIES = ["capdb", "ssl", "crypto", "pthread", "m"]
CAPDB_LIBRARY_DIRS = ["$CAPDB_BUILD"]
EOF

cat <<EOF
# CapDB Python build environment configured
# Include directories: $CAPDB_CLIENT:$CAPDB_GENERATED
# Library directory: $CAPDB_BUILD
# Libraries: libcapdb shared library, libssl, libcrypto, libpthread, libm
export CAPDB_BUILD="$CAPDB_BUILD"
export CAPDB_BUILD_DIR="$CAPDB_BUILD"
export CAPDB_LIBRARY="$CAPDB_BUILD/libcapdb.so"
export CAPDB_CLIENT_LIBRARY="$CAPDB_BUILD/libcapdb.so"
export CAPDB_INCLUDE_DIR="$CAPDB_CLIENT"
export CAPDB_GENERATED_DIR="$CAPDB_GENERATED"
export LD_LIBRARY_PATH="$CAPDB_BUILD:$LD_LIBRARY_PATH"
EOF
