#!/usr/bin/env python3
"""Port of tool/mkctimec.tcl — generate ctime.c compile-option diagnostics."""
from __future__ import annotations

import argparse
from pathlib import Path


HEAD_WARNING = """/* DO NOT EDIT!
** This file is automatically generated by the script in the canonical
** CapDB source tree at tools/py/mkctimec.py.
**
** To modify this header, edit any of the various lists in that script
** which specify categories of generated conditionals in this file.
*/"""

HEAD_CODE = """
/*
** 2010 February 23
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
**
** This file implements routines used to report what compile-time options
** CapDB was built with.
*/
#ifndef CAPDB_OMIT_COMPILEOPTION_DIAGS /* IMP: R-16824-07538 */

/*
** Include the configuration header output by 'configure' if we're using the
** autoconf-based build
*/
#if defined(_HAVE_CAPDB_CONFIG_H) && !defined(CAPDBCONFIG_H)
#include "capdb_cfg.h"
#define CAPDBCONFIG_H 1
#endif

/* These macros are provided to "stringify" the value of the define
** for those options in which the value is meaningful. */
#define CTIMEOPT_VAL_(opt) #opt
#define CTIMEOPT_VAL(opt) CTIMEOPT_VAL_(opt)

/* Like CTIMEOPT_VAL, but especially for CAPDB_DEFAULT_LOOKASIDE. This
** option requires a separate macro because legal values contain a single
** comma. e.g. (-DCAPDB_DEFAULT_LOOKASIDE="100,100") */
#define CTIMEOPT_VAL2_(opt1,opt2) #opt1 "," #opt2
#define CTIMEOPT_VAL2(opt) CTIMEOPT_VAL2_(opt)
#include "capdbInt.h"

/*
** An array of names of all compile-time options.  This array should
** be sorted A-Z.
**
** This array looks large, but in a typical installation actually uses
** only a handful of compile-time options, so most times this array is usually
** rather short and uses little memory space.
*/
static const char * const capdbazCompileOpt[] = {
"""

TAIL_CODE = """
};

const char **capdbCompileOptions(int *pnOpt){
  *pnOpt = sizeof(capdbazCompileOpt) / sizeof(capdbazCompileOpt[0]);
  return (const char**)capdbazCompileOpt;
}

#endif /* CAPDB_OMIT_COMPILEOPTION_DIAGS */
"""

BOOLEAN_DEFNNZ_OPTIONS = [
    ("CAPDB_HOMEGROWN_RECURSIVE_MUTEX", 1),
    ("CAPDB_POWERSAFE_OVERWRITE", 1),
    ("CAPDB_DEFAULT_MEMSTATUS", 1),
    ("CAPDB_OMIT_TRACE", 1),
    ("CAPDB_ALLOW_COVERING_INDEX_SCAN", 1),
]

BOOLEAN_DEFNIL_OPTIONS = [
    "CAPDB_32BIT_ROWID",
    "CAPDB_4_BYTE_ALIGNED_MALLOC",
    "CAPDB_ALLOW_ROWID_IN_VIEW",
    "CAPDB_ALLOW_URI_AUTHORITY",
    "CAPDB_BUG_COMPATIBLE_20160819",
    "CAPDB_BUG_COMPATIBLE_20250510",
    "CAPDB_CASE_SENSITIVE_LIKE",
    "CAPDB_CHECK_PAGES",
    "CAPDB_COVERAGE_TEST",
    "CAPDB_DEBUG",
    "CAPDB_DEFAULT_AUTOMATIC_INDEX",
    "CAPDB_DEFAULT_AUTOVACUUM",
    "CAPDB_DEFAULT_CKPTFULLFSYNC",
    "CAPDB_DEFAULT_FOREIGN_KEYS",
    "CAPDB_DEFAULT_LOCKING_MODE",
    "CAPDB_DEFAULT_RECURSIVE_TRIGGERS",
    "CAPDB_DEFAULT_SYNCHRONOUS",
    "CAPDB_DEFAULT_WAL_SYNCHRONOUS",
    "CAPDB_DIRECT_OVERFLOW_READ",
    "CAPDB_DISABLE_DIRSYNC",
    "CAPDB_DISABLE_FTS3_UNICODE",
    "CAPDB_DISABLE_FTS4_DEFERRED",
    "CAPDB_DISABLE_INTRINSIC",
    "CAPDB_DISABLE_LFS",
    "CAPDB_DISABLE_PAGECACHE_OVERFLOW_STATS",
    "CAPDB_DISABLE_SKIPAHEAD_DISTINCT",
    "CAPDB_ENABLE_8_3_NAMES",
    "CAPDB_ENABLE_API_ARMOR",
    "CAPDB_ENABLE_ATOMIC_WRITE",
    "CAPDB_ENABLE_BATCH_ATOMIC_WRITE",
    "CAPDB_ENABLE_BYTECODE_VTAB",
    "CAPDB_ENABLE_CARRAY",
    "CAPDB_ENABLE_COLUMN_METADATA",
    "CAPDB_ENABLE_COLUMN_USED_MASK",
    "CAPDB_ENABLE_COSTMULT",
    "CAPDB_ENABLE_CURSOR_HINTS",
    "CAPDB_ENABLE_DBPAGE_VTAB",
    "CAPDB_ENABLE_DBSTAT_VTAB",
    "CAPDB_ENABLE_EXPENSIVE_ASSERT",
    "CAPDB_ENABLE_EXPLAIN_COMMENTS",
    "CAPDB_ENABLE_FTS3",
    "CAPDB_ENABLE_FTS3_PARENTHESIS",
    "CAPDB_ENABLE_FTS3_TOKENIZER",
    "CAPDB_ENABLE_FTS4",
    "CAPDB_ENABLE_FTS5",
    "CAPDB_ENABLE_GEOPOLY",
    "CAPDB_ENABLE_HIDDEN_COLUMNS",
    "CAPDB_ENABLE_ICU",
    "CAPDB_ENABLE_IOTRACE",
    "CAPDB_ENABLE_LOAD_EXTENSION",
    "CAPDB_ENABLE_LOCKING_STYLE",
    "CAPDB_ENABLE_MATH_FUNCTIONS",
    "CAPDB_ENABLE_MEMORY_MANAGEMENT",
    "CAPDB_ENABLE_MEMSYS3",
    "CAPDB_ENABLE_MEMSYS5",
    "CAPDB_ENABLE_MULTIPLEX",
    "CAPDB_ENABLE_NETWORK",
    "CAPDB_ENABLE_NORMALIZE",
    "CAPDB_ENABLE_NULL_TRIM",
    "CAPDB_ENABLE_ORDERED_SET_AGGREGATES",
    "CAPDB_ENABLE_OFFSET_SQL_FUNC",
    "CAPDB_ENABLE_OVERSIZE_CELL_CHECK",
    "CAPDB_ENABLE_PERCENTILE",
    "CAPDB_ENABLE_POOL",
    "CAPDB_ENABLE_PREUPDATE_HOOK",
    "CAPDB_ENABLE_QPSG",
    "CAPDB_ENABLE_RBU",
    "CAPDB_ENABLE_RTREE",
    "CAPDB_ENABLE_SESSION",
    "CAPDB_ENABLE_SETLK_TIMEOUT",
    "CAPDB_ENABLE_SNAPSHOT",
    "CAPDB_ENABLE_SORTER_REFERENCES",
    "CAPDB_ENABLE_SQLLOG",
    "CAPDB_ENABLE_STAT4",
    "CAPDB_ENABLE_STMT_SCANSTATUS",
    "CAPDB_ENABLE_STMTVTAB",
    "CAPDB_ENABLE_TREETRACE",
    "CAPDB_ENABLE_UNKNOWN_SQL_FUNCTION",
    "CAPDB_ENABLE_UNLOCK_NOTIFY",
    "CAPDB_ENABLE_UPDATE_DELETE_LIMIT",
    "CAPDB_ENABLE_URI_00_ERROR",
    "CAPDB_ENABLE_VFSTRACE",
    "CAPDB_ENABLE_WHERETRACE",
    "CAPDB_ENABLE_ZIPVFS",
    "CAPDB_EXPLAIN_ESTIMATED_ROWS",
    "CAPDB_EXTRA_IFNULLROW",
    "CAPDB_FTS5_ENABLE_TEST_MI",
    "CAPDB_FTS5_NO_WITHOUT_ROWID",
    "CAPDB_IGNORE_AFP_LOCK_ERRORS",
    "CAPDB_IGNORE_FLOCK_LOCK_ERRORS",
    "CAPDB_INLINE_MEMCPY",
    "CAPDB_INT64_TYPE",
    "CAPDB_LEGACY_JSON_VALID",
    "CAPDB_LIKE_DOESNT_MATCH_BLOBS",
    "CAPDB_LOCK_TRACE",
    "CAPDB_LOG_CACHE_SPILL",
    "CAPDB_MEMDEBUG",
    "CAPDB_MIXED_ENDIAN_64BIT_FLOAT",
    "CAPDB_MMAP_READWRITE",
    "CAPDB_MUTEX_NOOP",
    "CAPDB_MUTEX_OMIT",
    "CAPDB_MUTEX_PTHREADS",
    "CAPDB_MUTEX_W32",
    "CAPDB_NEED_ERR_NAME",
    "CAPDB_NO_SYNC",
    "CAPDB_OMIT_ALTERTABLE",
    "CAPDB_OMIT_ANALYZE",
    "CAPDB_OMIT_ATTACH",
    "CAPDB_OMIT_AUTHORIZATION",
    "CAPDB_OMIT_AUTOINCREMENT",
    "CAPDB_OMIT_AUTOINIT",
    "CAPDB_OMIT_AUTOMATIC_INDEX",
    "CAPDB_OMIT_AUTORESET",
    "CAPDB_OMIT_AUTOVACUUM",
    "CAPDB_OMIT_BETWEEN_OPTIMIZATION",
    "CAPDB_OMIT_BLOB_LITERAL",
    "CAPDB_OMIT_CAST",
    "CAPDB_OMIT_CHECK",
    "CAPDB_OMIT_COMPLETE",
    "CAPDB_OMIT_COMPOUND_SELECT",
    "CAPDB_OMIT_CONFLICT_CLAUSE",
    "CAPDB_OMIT_CTE",
    "CAPDB_OMIT_DECLTYPE",
    "CAPDB_OMIT_DEPRECATED",
    "CAPDB_OMIT_DESERIALIZE",
    "CAPDB_OMIT_DISKIO",
    "CAPDB_OMIT_EXPLAIN",
    "CAPDB_OMIT_FLAG_PRAGMAS",
    "CAPDB_OMIT_FLOATING_POINT",
    "CAPDB_OMIT_FOREIGN_KEY",
    "CAPDB_OMIT_GET_TABLE",
    "CAPDB_OMIT_HEX_INTEGER",
    "CAPDB_OMIT_INCRBLOB",
    "CAPDB_OMIT_INTEGRITY_CHECK",
    "CAPDB_OMIT_INTROSPECTION_PRAGMAS",
    "CAPDB_OMIT_JSON",
    "CAPDB_OMIT_LIKE_OPTIMIZATION",
    "CAPDB_OMIT_LOAD_EXTENSION",
    "CAPDB_OMIT_LOCALTIME",
    "CAPDB_OMIT_LOOKASIDE",
    "CAPDB_OMIT_MEMORYDB",
    "CAPDB_OMIT_OR_OPTIMIZATION",
    "CAPDB_OMIT_PAGER_PRAGMAS",
    "CAPDB_OMIT_PARSER_TRACE",
    "CAPDB_OMIT_POPEN",
    "CAPDB_OMIT_PRAGMA",
    "CAPDB_OMIT_PROGRESS_CALLBACK",
    "CAPDB_OMIT_QUICKBALANCE",
    "CAPDB_OMIT_REINDEX",
    "CAPDB_OMIT_SCHEMA_PRAGMAS",
    "CAPDB_OMIT_SCHEMA_VERSION_PRAGMAS",
    "CAPDB_OMIT_SEH",
    "CAPDB_OMIT_SHARED_CACHE",
    "CAPDB_OMIT_SHUTDOWN_DIRECTORIES",
    "CAPDB_OMIT_SUBQUERY",
    "CAPDB_OMIT_TCL_VARIABLE",
    "CAPDB_OMIT_TEMPDB",
    "CAPDB_OMIT_TEST_CONTROL",
    "CAPDB_OMIT_TRIGGER",
    "CAPDB_OMIT_TRUNCATE_OPTIMIZATION",
    "CAPDB_OMIT_UTF16",
    "CAPDB_OMIT_VACUUM",
    "CAPDB_OMIT_VIEW",
    "CAPDB_OMIT_VIRTUALTABLE",
    "CAPDB_OMIT_WAL",
    "CAPDB_OMIT_WSD",
    "CAPDB_OMIT_XFER_OPT",
    "CAPDB_PERFORMANCE_TRACE",
    "CAPDB_PREFER_PROXY_LOCKING",
    "CAPDB_PROXY_DEBUG",
    "CAPDB_REVERSE_UNORDERED_SELECTS",
    "CAPDB_RTREE_INT_ONLY",
    "CAPDB_SECURE_DELETE",
    "CAPDB_SMALL_STACK",
    "CAPDB_SOUNDEX",
    "CAPDB_STRICT_SUBTYPE",
    "CAPDB_SUBSTR_COMPATIBILITY",
    "CAPDB_TCL",
    "CAPDB_TEST",
    "CAPDB_UNLINK_AFTER_CLOSE",
    "CAPDB_UNTESTABLE",
    "CAPDB_USE_ALLOCA",
    "CAPDB_USE_FCNTL_TRACE",
    "CAPDB_USE_URI",
    "CAPDB_VDBE_COVERAGE",
    "CAPDB_WIN32_MALLOC",
    "CAPDB_ZERO_MALLOC",
]

VALUE2_OPTIONS = ["CAPDB_DEFAULT_LOOKASIDE"]

VALUE_OPTIONS = [
    "CAPDB_ATOMIC_INTRINSICS",
    "CAPDB_BITMASK_TYPE",
    "CAPDB_DEFAULT_CACHE_SIZE",
    "CAPDB_DEFAULT_FILE_FORMAT",
    "CAPDB_DEFAULT_FILE_PERMISSIONS",
    "CAPDB_DEFAULT_JOURNAL_SIZE_LIMIT",
    "CAPDB_DEFAULT_LOCKING_MODE",
    "CAPDB_DEFAULT_MMAP_SIZE",
    "CAPDB_DEFAULT_PAGE_SIZE",
    "CAPDB_DEFAULT_PCACHE_INITSZ",
    "CAPDB_DEFAULT_PROXYDIR_PERMISSIONS",
    "CAPDB_DEFAULT_ROWEST",
    "CAPDB_DEFAULT_SECTOR_SIZE",
    "CAPDB_DEFAULT_SYNCHRONOUS",
    "CAPDB_DEFAULT_WAL_AUTOCHECKPOINT",
    "CAPDB_DEFAULT_WAL_SYNCHRONOUS",
    "CAPDB_DEFAULT_WORKER_THREADS",
    "CAPDB_DQS",
    "CAPDB_ENABLE_8_3_NAMES",
    "CAPDB_ENABLE_CEROD",
    "CAPDB_ENABLE_LOCKING_STYLE",
    "CAPDB_EXTRA_AUTOEXT",
    "CAPDB_EXTRA_INIT",
    "CAPDB_EXTRA_INIT_MUTEXED",
    "CAPDB_EXTRA_SHUTDOWN",
    "CAPDB_FTS3_MAX_EXPR_DEPTH",
    "CAPDB_INTEGRITY_CHECK_ERROR_MAX",
    "CAPDB_MALLOC_SOFT_LIMIT",
    "CAPDB_MAX_ATTACHED",
    "CAPDB_MAX_COLUMN",
    "CAPDB_MAX_COMPOUND_SELECT",
    "CAPDB_MAX_DEFAULT_PAGE_SIZE",
    "CAPDB_MAX_EXPR_DEPTH",
    "CAPDB_MAX_FUNCTION_ARG",
    "CAPDB_MAX_LENGTH",
    "CAPDB_MAX_LIKE_PATTERN_LENGTH",
    "CAPDB_MAX_MEMORY",
    "CAPDB_MAX_MMAP_SIZE",
    "CAPDB_MAX_MMAP_SIZE_",
    "CAPDB_MAX_PAGE_COUNT",
    "CAPDB_MAX_PAGE_SIZE",
    "CAPDB_MAX_SCHEMA_RETRY",
    "CAPDB_MAX_SQL_LENGTH",
    "CAPDB_MAX_TRIGGER_DEPTH",
    "CAPDB_MAX_VARIABLE_NUMBER",
    "CAPDB_MAX_VDBE_OP",
    "CAPDB_MAX_WORKER_THREADS",
    "CAPDB_SORTER_PMASZ",
    "CAPDB_STAT4_SAMPLES",
    "CAPDB_STMTJRNL_SPILL",
    "CAPDB_TEMP_STORE",
]


def trim_name(symbol: str) -> str:
    return symbol[7:] if symbol.startswith("CAPDB_") else symbol


def build_options() -> dict[str, str]:
    options: dict[str, str] = {}

    options["COMPILER"] = """#if defined(__clang__) && defined(__clang_major__)
  "COMPILER=clang-" CTIMEOPT_VAL(__clang_major__) "."
                    CTIMEOPT_VAL(__clang_minor__) "."
                    CTIMEOPT_VAL(__clang_patchlevel__),
#elif defined(_MSC_VER)
  "COMPILER=msvc-" CTIMEOPT_VAL(_MSC_VER),
#elif defined(__GNUC__) && defined(__VERSION__)
  "COMPILER=gcc-" __VERSION__,
#endif"""

    options["HAVE_ISNAN"] = """#if HAVE_ISNAN || CAPDB_HAVE_ISNAN
  "HAVE_ISNAN",
#endif"""

    options["OMIT_DATETIME_FUNCS"] = """#if defined(CAPDB_OMIT_DATETIME_FUNCS) || defined(CAPDB_OMIT_FLOATING_POINT)
  "OMIT_DATETIME_FUNCS",
#endif"""

    options["SYSTEM_MALLOC"] = """#if (!defined(CAPDB_WIN32_MALLOC) \\
     && !defined(CAPDB_ZERO_MALLOC) \\
     && !defined(CAPDB_MEMDEBUG) \\
    ) || defined(CAPDB_SYSTEM_MALLOC)
  "SYSTEM_MALLOC",
#endif"""

    options["THREADSAFE"] = """#if defined(CAPDB_THREADSAFE)
  "THREADSAFE=" CTIMEOPT_VAL(CAPDB_THREADSAFE),
#elif defined(THREADSAFE)
  "THREADSAFE=" CTIMEOPT_VAL(THREADSAFE),
#else
  "THREADSAFE=1",
#endif"""

    for sym, defval in BOOLEAN_DEFNNZ_OPTIONS:
        name = trim_name(sym)
        options[name] = f"""#ifdef {sym}
# if {sym} != {defval}
  "{name}=" CTIMEOPT_VAL({sym}),
# endif
#endif"""

    for sym in BOOLEAN_DEFNIL_OPTIONS:
        name = trim_name(sym)
        options[name] = f"""#ifdef {sym}
  "{name}",
#endif"""

    for sym in VALUE_OPTIONS:
        name = trim_name(sym)
        options[name] = f"""#ifdef {sym}
  "{name}=" CTIMEOPT_VAL({sym}),
#endif"""

    for sym in VALUE2_OPTIONS:
        name = trim_name(sym)
        options[name] = f"""#ifdef {sym}
  "{name}=" CTIMEOPT_VAL2({sym}),
#endif"""

    return options


def generate_ctime_c() -> str:
    parts = [HEAD_WARNING, HEAD_CODE]
    for key in sorted(build_options().keys()):
        parts.append(build_options()[key].strip())
    parts.append(TAIL_CODE)
    return "\n".join(parts)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "output",
        nargs="?",
        type=Path,
        default=Path("ctime.c"),
        help="Output path (default: ctime.c)",
    )
    args = p.parse_args(argv)
    args.output.write_text(generate_ctime_c(), encoding="utf-8", newline="\n")
    if args.output.name == "ctime.c":
        print(f"Overwriting {args.output}...")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
