#!/usr/bin/env python3
"""Port of tool/mkshellc.tcl — assemble core/shell.c.in into shell.c."""
from __future__ import annotations

import argparse
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]


def resolve_include(spec: str, repo_root: Path) -> tuple[str, Path]:
    if spec.startswith("../ext/capdb/"):
        rel = "capdb/" + spec[len("../ext/capdb/") :]
    elif spec.startswith("../ext/"):
        rel = "extensions/" + spec[len("../ext/") :]
    elif spec.startswith("../"):
        rel = spec[3:]
    else:
        rel = f"core/{spec}"
    return rel, repo_root / rel


def collect_usage(shell_in: Path, repo_root: Path) -> tuple[dict[str, str], dict[str, bool]]:
    all_source: dict[str, bool] = {"core/shell.c.in": True}
    usage: dict[str, str] = {}
    in_usage = False
    dotcmd = ""
    details = ""

    for line in shell_in.read_text(encoding="utf-8", errors="surrogateescape").splitlines():
        if line.startswith("INCLUDE "):
            _, spec = line.split(None, 1)
            rel, _ = resolve_include(spec.strip(), repo_root)
            all_source[rel] = True
        elif m := re.match(r"^\*\* USAGE:\s+(\S+)", line):
            in_usage = True
            dotcmd = m.group(1)
            details = line[2:].strip()
        elif in_usage:
            if not line.startswith("**") or " DOT-COMMAND: " in line:
                in_usage = False
                if dotcmd:
                    usage[dotcmd] = details.strip()
            else:
                details += "\n" + line[3:].rstrip()

    return usage, all_source


def generate_usage(usage: dict[str, str]) -> str:
    lines = [
        "/**************************************************************",
        '** "Usage" help text automatically generated from comments */',
        "static const struct {",
        "  const char *zCmd;   /* Name of the dot-command */",
        "  const char *zUsage; /* Documentation */",
        "} aUsage[] = {",
    ]
    for dotcmd in sorted(usage):
        lines.append(f'  {{ "{dotcmd}",')
        for part in usage[dotcmd].splitlines():
            esc = part.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'"{esc}\\n"')
        lines.append("  },")
    lines.append("};")
    return "\n".join(lines)


def omit_redundant_typedefs(line: str, seen: dict[str, bool]) -> str:
    m = re.match(r"^typedef .* ([a-zA-Z0-9_]+);", line)
    if m:
        typename = m.group(1)
        if seen.get(typename):
            commented = line.replace("/*", "//").replace("*/", "//")
            return f"/* {commented} */"
        seen[typename] = True
    return line


def generate_shell_c(
    *,
    repo_root: Path,
    shell_in: Path | None = None,
) -> str:
    shell_in = shell_in or repo_root / "core" / "shell.c.in"
    usage, all_source = collect_usage(shell_in, repo_root)
    typedef_seen: dict[str, bool] = {}
    out: list[str] = [
        "/*",
        '** This is the amalgamated source code to the "capdb" or "capdb.exe"',
        "** command-line shell (CLI) for CapDB.  This file is automatically",
        "** generated by the tools/py/mkshellc.py script from the following sources:",
        "**",
    ]
    for fn in sorted(all_source):
        out.append(f"**   {fn}")
    out.extend(
        [
            "**",
            "** To modify this program, edit core/shell.c.in and/or the files",
            '** listed above, then rerun "python3 tools/py/mkshellc.py shell.c".',
            "*/",
            "/************************* Begin core/shell.c.in ******************/",
        ]
    )

    i_line = 0
    for raw in shell_in.read_text(encoding="utf-8", errors="surrogateescape").splitlines():
        i_line += 1
        lx = omit_redundant_typedefs(raw, typedef_seen)
        if lx.startswith("INCLUDE "):
            spec = lx.split()[1]
            rel, full = resolve_include(spec, repo_root)
            out.append(f"/************************* Begin {rel} ******************/")
            if full.is_file():
                for inner in full.read_text(
                    encoding="utf-8", errors="surrogateescape"
                ).splitlines():
                    inner = omit_redundant_typedefs(inner, typedef_seen)
                    if re.match(r'^# *include "capdb', inner) or re.match(
                        r'^# *include "windirent.h"', inner
                    ):
                        inner = f"/* {inner} */"
                    inner = inner.replace("__declspec(dllexport)", "")
                    out.append(inner)
            out.append(f"/************************* End {rel} ********************/")
        elif lx.startswith("INSERT-USAGE-TEXT-HERE"):
            out.append(generate_usage(usage))
        else:
            out.append(lx)

    out.append("/************************* End core/shell.c.in ******************/")
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "output",
        nargs="?",
        type=Path,
        help="Output file (default: stdout)",
    )
    p.add_argument(
        "--repo-root",
        type=Path,
        default=REPO_ROOT,
        help="Repository root",
    )
    p.add_argument(
        "--shell-in",
        type=Path,
        help="Override path to shell.c.in",
    )
    args = p.parse_args(argv)

    result = generate_shell_c(
        repo_root=args.repo_root,
        shell_in=args.shell_in,
    )
    if args.output:
        args.output.write_text(result, encoding="utf-8", newline="\n")
    else:
        import sys

        sys.stdout.write(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
