#!/usr/bin/env python3
"""Port of tool/vdbe-compress.tcl — stack-union transform for vdbe.c."""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


def compress_vdbe(text: str, *, small_stack: bool) -> str:
    if not small_stack:
        return text

    lines = text.splitlines(keepends=True)
    out_before: list[str] = []
    union_def: list[str] = []
    out_after: list[str] = []
    s_ctr = 0
    namechars = "abcefghjklmnopqrstuvwxyz"
    nnc = len(namechars)

    idx = 0
    while idx < len(lines):
        line = lines[idx]
        if "INSERT STACK UNION HERE" in line:
            idx += 1
            break
        out_before.append(line)
        idx += 1

    vlist: list[str] = []
    seen_decl = False
    sname = ""

    case_re = re.compile(r"^case (OP_\w+): \{")
    decl_re = re.compile(r"^ +(const )?\w+ \**(\w+)(\[.*\])?;")
    endif_re = re.compile(r"^#(if|endif)")

    while idx < len(lines):
        line = lines[idx]
        m = case_re.match(line.rstrip("\n"))
        if m:
            operator = m.group(1)
            out_after.append(line)
            idx += 1
            vlist = []
            while idx < len(lines):
                line = lines[idx]
                dm = decl_re.match(line.rstrip("\n"))
                if dm:
                    if not seen_decl:
                        sname = (
                            namechars[s_ctr // nnc]
                            + namechars[s_ctr % nnc]
                        )
                        s_ctr += 1
                        union_def.append(
                            f"    struct {operator}_stack_vars {{\n"
                        )
                        out_after.append(
                            f"#if 0  /* local variables moved into u.{sname} */\n"
                        )
                        seen_decl = True
                    union_def.append(f"    {line.rstrip()}\n")
                    out_after.append(line)
                    vlist.append(dm.group(2))
                    idx += 1
                elif endif_re.match(line.rstrip("\n")) and vlist:
                    union_def.append(line)
                    out_after.append(line)
                    idx += 1
                else:
                    break
            if seen_decl:
                union_def.append(f"    }} {sname};\n")
                out_after.append(
                    f"#endif /* local variables moved into u.{sname} */\n"
                )
            seen_decl = False
            continue

        stripped = line.rstrip("\n")
        if stripped == "}":
            out_after.append(line)
            vlist = []
            idx += 1
            continue

        if vlist:
            patched = line
            for v in vlist:
                patched = re.sub(
                    rf"([^a-zA-Z0-9>.]){re.escape(v)}(\W)",
                    rf"\1u.{sname}.\2",
                    patched,
                )
                patched = re.sub(
                    rf"([^a-zA-Z0-9>.]){re.escape(v)}(\W)",
                    rf"\1u.{sname}.\2",
                    patched,
                )
                patched = re.sub(
                    rf"([^-])>{re.escape(v)}(\W)",
                    rf"\1>u.{sname}.\2",
                    patched,
                )
            out_after.append(patched.rstrip("\n") + ("\n" if line.endswith("\n") else ""))
            idx += 1
            continue

        out_after.append(line)
        idx += 1

    header = (
        "  /********************************************************************\n"
        "  ** Automatically generated code\n"
        "  **\n"
        "  ** The following union is automatically generated by the\n"
        "  ** vdbe_compress.py script.  The purpose of this union is to\n"
        "  ** reduce the amount of stack space required by this function.\n"
        "  ** See comments in the vdbe-compress.tcl script for details.\n"
        "  */\n"
        "  union vdbeExecUnion {\n"
    )
    footer = (
        "  } u;\n"
        "  /* End automatically generated code\n"
        "  ********************************************************************/\n"
    )
    return (
        "".join(out_before)
        + header
        + "".join(union_def)
        + footer
        + "".join(out_after)
    )


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "input",
        nargs="?",
        type=Path,
        help="vdbe.c input (default: stdin)",
    )
    p.add_argument(
        "output",
        nargs="?",
        type=Path,
        help="vdbe.c output (default: stdout)",
    )
    p.add_argument(
        "--small-stack",
        action="store_true",
        help="Apply CAPDB_SMALL_STACK / SQLITE_SMALL_STACK transform",
    )
    p.add_argument(
        "cflags",
        nargs="*",
        help="CFLAGS tokens; CAPDB_SMALL_STACK or SQLITE_SMALL_STACK enables transform",
    )
    args = p.parse_args(argv)

    small_stack = args.small_stack
    for flag in args.cflags:
        if "CAPDB_SMALL_STACK" in flag or "SQLITE_SMALL_STACK" in flag:
            small_stack = True

    if args.input:
        text = args.input.read_text(encoding="utf-8", errors="surrogateescape")
    else:
        text = sys.stdin.read()

    result = compress_vdbe(text, small_stack=small_stack)

    if args.output:
        args.output.write_text(result, encoding="utf-8", newline="\n")
    else:
        sys.stdout.write(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
