/*
** 2001 September 15
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Header file for the Virtual DataBase Engine (VDBE)
**
** This header defines the interface to the virtual database engine
** or VDBE.  The VDBE implements an abstract machine that runs a
** simple program to access and modify the underlying database.
*/
#ifndef CAPDB_VDBE_H
#define CAPDB_VDBE_H
#include <stdio.h>

/*
** A single VDBE is an opaque structure named "Vdbe".  Only routines
** in the source file sqliteVdbe.c are allowed to see the insides
** of this structure.
*/
typedef struct Vdbe Vdbe;

/*
** The names of the following types declared in vdbeInt.h are required
** for the VdbeOp definition.
*/
typedef struct capdb_value Mem;
typedef struct SubProgram SubProgram;
typedef struct SubrtnSig SubrtnSig;

/*
** A signature for a reusable subroutine that materializes the RHS of
** an IN operator.
*/
struct SubrtnSig {
  int selId;          /* SELECT-id for the SELECT statement on the RHS */
  u8 bComplete;       /* True if fully coded and available for reusable */
  char *zAff;         /* Affinity of the overall IN expression */
  int iTable;         /* Ephemeral table generated by the subroutine */
  int iAddr;          /* Subroutine entry address */
  int regReturn;      /* Register used to hold return address */
};

/*
** A single instruction of the virtual machine has an opcode
** and as many as three operands.  The instruction is recorded
** as an instance of the following structure:
*/
struct VdbeOp {
  u8 opcode;          /* What operation to perform */
  signed char p4type; /* One of the P4_xxx constants for p4 */
  u16 p5;             /* Fifth parameter is an unsigned 16-bit integer */
  int p1;             /* First operand */
  int p2;             /* Second parameter (often the jump destination) */
  int p3;             /* The third parameter */
  union p4union {     /* fourth parameter */
    int i;                 /* Integer value if p4type==P4_INT32 */
    void *p;               /* Generic pointer */
    char *z;               /* Pointer to data for string (char array) types */
    i64 *pI64;             /* Used when p4type is P4_INT64 */
    double *pReal;         /* Used when p4type is P4_REAL */
    FuncDef *pFunc;        /* Used when p4type is P4_FUNCDEF */
    capdb_context *pCtx; /* Used when p4type is P4_FUNCCTX */
    CollSeq *pColl;        /* Used when p4type is P4_COLLSEQ */
    Mem *pMem;             /* Used when p4type is P4_MEM */
    VTable *pVtab;         /* Used when p4type is P4_VTAB */
    KeyInfo *pKeyInfo;     /* Used when p4type is P4_KEYINFO */
    u32 *ai;               /* Used when p4type is P4_INTARRAY */
    SubProgram *pProgram;  /* Used when p4type is P4_SUBPROGRAM */
    Table *pTab;           /* Used when p4type is P4_TABLE */
    SubrtnSig *pSubrtnSig; /* Used when p4type is P4_SUBRTNSIG */
    Index *pIdx;           /* Used when p4type is P4_INDEX */
#ifdef CAPDB_ENABLE_CURSOR_HINTS
    Expr *pExpr;           /* Used when p4type is P4_EXPR */
#endif
  } p4;
#ifdef CAPDB_ENABLE_EXPLAIN_COMMENTS
  char *zComment;          /* Comment to improve readability */
#endif
#ifdef CAPDB_VDBE_COVERAGE
  u32 iSrcLine;            /* Source-code line that generated this opcode
                           ** with flags in the upper 8 bits */
#endif
#if defined(CAPDB_ENABLE_STMT_SCANSTATUS) || defined(VDBE_PROFILE)
  u64 nExec;
  u64 nCycle;
#endif
};
typedef struct VdbeOp VdbeOp;


/*
** A sub-routine used to implement a trigger program.
*/
struct SubProgram {
  VdbeOp *aOp;                  /* Array of opcodes for sub-program */
  int nOp;                      /* Elements in aOp[] */
  int nMem;                     /* Number of memory cells required */
  int nCsr;                     /* Number of cursors required */
  u8 *aOnce;                    /* Array of OP_Once flags */
  void *token;                  /* id that may be used to recursive triggers */
  SubProgram *pNext;            /* Next sub-program already visited */
};

/*
** A smaller version of VdbeOp used for the VdbeAddOpList() function because
** it takes up less space.
*/
struct VdbeOpList {
  u8 opcode;          /* What operation to perform */
  signed char p1;     /* First operand */
  signed char p2;     /* Second parameter (often the jump destination) */
  signed char p3;     /* Third parameter */
};
typedef struct VdbeOpList VdbeOpList;

/*
** Allowed values of VdbeOp.p4type
*/
#define P4_NOTUSED      0   /* The P4 parameter is not used */
#define P4_TRANSIENT    0   /* P4 is a pointer to a transient string */
#define P4_STATIC     (-1)  /* Pointer to a static string */
#define P4_COLLSEQ    (-2)  /* P4 is a pointer to a CollSeq structure */
#define P4_INT32      (-3)  /* P4 is a 32-bit signed integer */
#define P4_SUBPROGRAM (-4)  /* P4 is a pointer to a SubProgram structure */
#define P4_TABLE      (-5)  /* P4 is a pointer to a Table structure */
#define P4_INDEX      (-6)  /* P4 is a pointer to an Index structure */
/* Above do not own any resources.  Must free those below */
#define P4_FREE_IF_LE (-7)
#define P4_DYNAMIC    (-7)  /* Pointer to memory from sqliteMalloc() */
#define P4_FUNCDEF    (-8)  /* P4 is a pointer to a FuncDef structure */
#define P4_KEYINFO    (-9)  /* P4 is a pointer to a KeyInfo structure */
#define P4_EXPR       (-10) /* P4 is a pointer to an Expr tree */
#define P4_MEM        (-11) /* P4 is a pointer to a Mem*    structure */
#define P4_VTAB       (-12) /* P4 is a pointer to an capdb_vtab structure */
#define P4_REAL       (-13) /* P4 is a 64-bit floating point value */
#define P4_INT64      (-14) /* P4 is a 64-bit signed integer */
#define P4_INTARRAY   (-15) /* P4 is a vector of 32-bit integers */
#define P4_FUNCCTX    (-16) /* P4 is a pointer to an capdb_context object */
#define P4_TABLEREF   (-17) /* Like P4_TABLE, but reference counted */
#define P4_SUBRTNSIG  (-18) /* P4 is a SubrtnSig pointer */

/* Error message codes for OP_Halt */
#define P5_ConstraintNotNull 1
#define P5_ConstraintUnique  2
#define P5_ConstraintCheck   3
#define P5_ConstraintFK      4

/*
** The Vdbe.aColName array contains 5n Mem structures, where n is the 
** number of columns of data returned by the statement.
*/
#define COLNAME_NAME     0
#define COLNAME_DECLTYPE 1
#define COLNAME_DATABASE 2
#define COLNAME_TABLE    3
#define COLNAME_COLUMN   4
#ifdef CAPDB_ENABLE_COLUMN_METADATA
# define COLNAME_N        5      /* Number of COLNAME_xxx symbols */
#else
# ifdef CAPDB_OMIT_DECLTYPE
#   define COLNAME_N      1      /* Store only the name */
# else
#   define COLNAME_N      2      /* Store the name and decltype */
# endif
#endif

/*
** The following macro converts a label returned by capdbVdbeMakeLabel()
** into an index into the Parse.aLabel[] array that contains the resolved
** address of that label.
*/
#define ADDR(X)  (~(X))

/*
** The makefile scans the vdbe.c source file and creates the "opcodes.h"
** header file that defines a number for each opcode used by the VDBE.
*/
#include "opcodes.h"

/*
** Additional non-public CAPDB_PREPARE_* flags
*/
#define CAPDB_PREPARE_SAVESQL  0x80  /* Preserve SQL text */
#define CAPDB_PREPARE_MASK     0x3f  /* Mask of public flags */

/*
** Prototypes for the VDBE interface.  See comments on the implementation
** for a description of what each of these routines does.
*/
Vdbe *capdbVdbeCreate(Parse*);
Parse *capdbVdbeParser(Vdbe*);
int capdbVdbeAddOp0(Vdbe*,int);
int capdbVdbeAddOp1(Vdbe*,int,int);
int capdbVdbeAddOp2(Vdbe*,int,int,int);
int capdbVdbeGoto(Vdbe*,int);
int capdbVdbeLoadString(Vdbe*,int,const char*);
void capdbVdbeMultiLoad(Vdbe*,int,const char*,...);
int capdbVdbeAddOp3(Vdbe*,int,int,int,int);
int capdbVdbeAddOp4(Vdbe*,int,int,int,int,const char *zP4,int);
int capdbVdbeAddOp4Dup8(Vdbe*,int,int,int,int,const u8*,int);
int capdbVdbeAddOp4Int(Vdbe*,int,int,int,int,int);
int capdbVdbeAddFunctionCall(Parse*,int,int,int,int,const FuncDef*,int);
void capdbVdbeEndCoroutine(Vdbe*,int);
#if defined(CAPDB_DEBUG) && !defined(CAPDB_TEST_REALLOC_STRESS)
  void capdbVdbeVerifyNoMallocRequired(Vdbe *p, int N);
  void capdbVdbeVerifyNoResultRow(Vdbe *p);
#else
# define capdbVdbeVerifyNoMallocRequired(A,B)
# define capdbVdbeVerifyNoResultRow(A)
#endif
#if defined(CAPDB_DEBUG)
  void capdbVdbeVerifyAbortable(Vdbe *p, int);
  void capdbVdbeNoJumpsOutsideSubrtn(Vdbe*,int,int,int);
#else
# define capdbVdbeVerifyAbortable(A,B)
# define capdbVdbeNoJumpsOutsideSubrtn(A,B,C,D)
#endif
VdbeOp *capdbVdbeAddOpList(Vdbe*, int nOp, VdbeOpList const *aOp,int iLineno);
#ifndef CAPDB_OMIT_EXPLAIN
  int capdbVdbeExplain(Parse*,u8,const char*,...);
  void capdbVdbeExplainPop(Parse*);
  int capdbVdbeExplainParent(Parse*);
# define ExplainQueryPlan(P)        capdbVdbeExplain P
# ifdef CAPDB_ENABLE_STMT_SCANSTATUS
#  define ExplainQueryPlan2(V,P)     (V = capdbVdbeExplain P)
# else
#  define ExplainQueryPlan2(V,P)     ExplainQueryPlan(P)
# endif
# define ExplainQueryPlanPop(P)     capdbVdbeExplainPop(P)
# define ExplainQueryPlanParent(P)  capdbVdbeExplainParent(P)
#else
# define ExplainQueryPlan(P)
# define ExplainQueryPlan2(V,P)
# define ExplainQueryPlanPop(P)
# define ExplainQueryPlanParent(P) 0
# define capdbExplainBreakpoint(A,B) /*no-op*/
#endif
#if defined(CAPDB_DEBUG) && !defined(CAPDB_OMIT_EXPLAIN)
  void capdbExplainBreakpoint(const char*,const char*);
#else
# define capdbExplainBreakpoint(A,B) /*no-op*/
#endif
void capdbVdbeAddParseSchemaOp(Vdbe*, int, char*, u16);
void capdbVdbeChangeOpcode(Vdbe*, int addr, u8);
void capdbVdbeChangeP1(Vdbe*, int addr, int P1);
void capdbVdbeChangeP2(Vdbe*, int addr, int P2);
void capdbVdbeChangeP3(Vdbe*, int addr, int P3);
void capdbVdbeChangeP5(Vdbe*, u16 P5);
void capdbVdbeTypeofColumn(Vdbe*, int);
void capdbVdbeJumpHere(Vdbe*, int addr);
void capdbVdbeJumpHereOrPopInst(Vdbe*, int addr);
int capdbVdbeChangeToNoop(Vdbe*, int addr);
int capdbVdbeDeletePriorOpcode(Vdbe*, u8 op);
#ifdef CAPDB_DEBUG
  void capdbVdbeReleaseRegisters(Parse*,int addr, int n, u32 mask, int);
#else
# define capdbVdbeReleaseRegisters(P,A,N,M,F)
#endif
void capdbVdbeChangeP4(Vdbe*, int addr, const char *zP4, int N);
void capdbVdbeAppendP4(Vdbe*, void *pP4, int p4type);
void capdbVdbeSetP4KeyInfo(Parse*, Index*);
void capdbVdbeUsesBtree(Vdbe*, int);
VdbeOp *capdbVdbeGetOp(Vdbe*, int);
VdbeOp *capdbVdbeGetLastOp(Vdbe*);
int capdbVdbeMakeLabel(Parse*);
void capdbVdbeRunOnlyOnce(Vdbe*);
void capdbVdbeReusable(Vdbe*);
void capdbVdbeDelete(Vdbe*);
void capdbVdbeMakeReady(Vdbe*,Parse*);
int capdbVdbeFinalize(Vdbe*);
void capdbVdbeResolveLabel(Vdbe*, int);
int capdbVdbeCurrentAddr(Vdbe*);
#ifdef CAPDB_DEBUG
  int capdbVdbeAssertMayAbort(Vdbe *, int);
#endif
void capdbVdbeResetStepResult(Vdbe*);
void capdbVdbeRewind(Vdbe*);
int capdbVdbeReset(Vdbe*);
void capdbVdbeSetNumCols(Vdbe*,int);
int capdbVdbeSetColName(Vdbe*, int, int, const char *, void(*)(void*));
void capdbVdbeCountChanges(Vdbe*);
capdb *capdbVdbeDb(Vdbe*);
u8 capdbVdbePrepareFlags(Vdbe*);
void capdbVdbeSetSql(Vdbe*, const char *z, int n, u8);
#ifdef CAPDB_ENABLE_NORMALIZE
void capdbVdbeAddDblquoteStr(capdb*,Vdbe*,const char*);
int capdbVdbeUsesDoubleQuotedString(Vdbe*,const char*);
#endif
void capdbVdbeSwap(Vdbe*,Vdbe*);
VdbeOp *capdbVdbeTakeOpArray(Vdbe*, int*, int*);
capdb_value *capdbVdbeGetBoundValue(Vdbe*, int, u8);
void capdbVdbeSetVarmask(Vdbe*, int);
#ifndef CAPDB_OMIT_TRACE
  char *capdbVdbeExpandSql(Vdbe*, const char*);
#endif
int capdbMemCompare(const Mem*, const Mem*, const CollSeq*);
int capdbBlobCompare(const Mem*, const Mem*);
#ifdef CAPDB_ENABLE_PERCENTILE
  const char *capdbVdbeFuncName(const capdb_context*);
#endif

void capdbVdbeRecordUnpack(int,const void*,UnpackedRecord*);
int capdbVdbeRecordCompare(int,const void*,UnpackedRecord*);
int capdbVdbeRecordCompareWithSkip(int, const void *, UnpackedRecord *, int);
UnpackedRecord *capdbVdbeAllocUnpackedRecord(KeyInfo*);

typedef int (*RecordCompare)(int,const void*,UnpackedRecord*);
RecordCompare capdbVdbeFindCompare(UnpackedRecord*);

void capdbVdbeLinkSubProgram(Vdbe *, SubProgram *);
int capdbVdbeHasSubProgram(Vdbe*);

void capdbMemSetArrayInt64(capdb_value *aMem, int iIdx, i64 val);

#ifndef CAPDB_OMIT_DATETIME_FUNCS
int capdbNotPureFunc(capdb_context*);
#endif
#ifdef CAPDB_ENABLE_BYTECODE_VTAB
int capdbVdbeBytecodeVtabInit(capdb*);
#endif

/* Use CAPDB_ENABLE_EXPLAIN_COMMENTS to enable generation of extra
** comments on each VDBE opcode.
**
** Use the CAPDB_ENABLE_MODULE_COMMENTS macro to see some extra no-op
** comments in VDBE programs that show key decision points in the code
** generator.
*/
#ifdef CAPDB_ENABLE_EXPLAIN_COMMENTS
  void capdbVdbeComment(Vdbe*, const char*, ...);
# define VdbeComment(X)  capdbVdbeComment X
  void capdbVdbeNoopComment(Vdbe*, const char*, ...);
# define VdbeNoopComment(X)  capdbVdbeNoopComment X
# ifdef CAPDB_ENABLE_MODULE_COMMENTS
#   define VdbeModuleComment(X)  capdbVdbeNoopComment X
# else
#   define VdbeModuleComment(X)
# endif
#else
# define VdbeComment(X)
# define VdbeNoopComment(X)
# define VdbeModuleComment(X)
#endif

/*
** The VdbeCoverage macros are used to set a coverage testing point
** for VDBE branch instructions.  The coverage testing points are line
** numbers in the capdb.c source file.  VDBE branch coverage testing
** only works with an amalgamation build.  That's ok since a VDBE branch
** coverage build designed for testing the test suite only.  No application
** should ever ship with VDBE branch coverage measuring turned on.
**
**    VdbeCoverage(v)                  // Mark the previously coded instruction
**                                     // as a branch
**
**    VdbeCoverageIf(v, conditional)   // Mark previous if conditional true
**
**    VdbeCoverageAlwaysTaken(v)       // Previous branch is always taken
**
**    VdbeCoverageNeverTaken(v)        // Previous branch is never taken
**
**    VdbeCoverageNeverNull(v)         // Previous three-way branch is only
**                                     // taken on the first two ways.  The
**                                     // NULL option is not possible
**
**    VdbeCoverageEqNe(v)              // Previous OP_Jump is only interested
**                                     // in distinguishing equal and not-equal.
**
** Every VDBE branch operation must be tagged with one of the macros above.
** If not, then when "make test" is run with -DCAPDB_VDBE_COVERAGE and
** -DCAPDB_DEBUG then an ALWAYS() will fail in the vdbeTakeBranch()
** routine in vdbe.c, alerting the developer to the missed tag.
**
** During testing, the test application will invoke
** capdb_test_control(CAPDB_TESTCTRL_VDBE_COVERAGE,...) to set a callback
** routine that is invoked as each bytecode branch is taken.  The callback
** contains the capdb.c source line number of the VdbeCoverage macro and
** flags to indicate whether or not the branch was taken.  The test application
** is responsible for keeping track of this and reporting byte-code branches
** that are never taken.
**
** See the VdbeBranchTaken() macro and vdbeTakeBranch() function in the
** vdbe.c source file for additional information.
*/
#ifdef CAPDB_VDBE_COVERAGE
  void capdbVdbeSetLineNumber(Vdbe*,int);
# define VdbeCoverage(v) capdbVdbeSetLineNumber(v,__LINE__)
# define VdbeCoverageIf(v,x) if(x)capdbVdbeSetLineNumber(v,__LINE__)
# define VdbeCoverageAlwaysTaken(v) \
         capdbVdbeSetLineNumber(v,__LINE__|0x5000000);
# define VdbeCoverageNeverTaken(v) \
         capdbVdbeSetLineNumber(v,__LINE__|0x6000000);
# define VdbeCoverageNeverNull(v) \
         capdbVdbeSetLineNumber(v,__LINE__|0x4000000);
# define VdbeCoverageNeverNullIf(v,x) \
         if(x)capdbVdbeSetLineNumber(v,__LINE__|0x4000000);
# define VdbeCoverageEqNe(v) \
         capdbVdbeSetLineNumber(v,__LINE__|0x8000000);
# define VDBE_OFFSET_LINENO(x) (__LINE__+x)
#else
# define VdbeCoverage(v)
# define VdbeCoverageIf(v,x)
# define VdbeCoverageAlwaysTaken(v)
# define VdbeCoverageNeverTaken(v)
# define VdbeCoverageNeverNull(v)
# define VdbeCoverageNeverNullIf(v,x)
# define VdbeCoverageEqNe(v)
# define VDBE_OFFSET_LINENO(x) 0
#endif

#ifdef CAPDB_ENABLE_STMT_SCANSTATUS
void capdbVdbeScanStatus(Vdbe*, int, int, int, LogEst, const char*);
void capdbVdbeScanStatusRange(Vdbe*, int, int, int);
void capdbVdbeScanStatusCounters(Vdbe*, int, int, int);
#else
# define capdbVdbeScanStatus(a,b,c,d,e,f)
# define capdbVdbeScanStatusRange(a,b,c,d)
# define capdbVdbeScanStatusCounters(a,b,c,d)
#endif

#if defined(CAPDB_DEBUG) || defined(VDBE_PROFILE)
void capdbVdbePrintOp(FILE*, int, VdbeOp*);
#endif

#if defined(CAPDB_ENABLE_CURSOR_HINTS) && defined(CAPDB_DEBUG)
int capdbCursorRangeHintExprCheck(Walker *pWalker, Expr *pExpr);
#endif

#endif /* CAPDB_VDBE_H */
