#!/usr/bin/make
#
# If the configure script does not work, then this Makefile is available
# as a backup.  Manually configure the variables below.
#
# Note:  This makefile works out-of-the-box on MacOS 10.2 (Jaguar)
#
CC = gcc
CFLAGS = -O0 -I.
LIBS = -lz
COPTS += -D_BSD_SOURCE
COPTS += -DCAPDB_ENABLE_LOCKING_STYLE=0
COPTS += -DCAPDB_THREADSAFE=0
COPTS += -DCAPDB_OMIT_LOAD_EXTENSION
COPTS += -DCAPDB_WITHOUT_ZONEMALLOC
COPTS += -DCAPDB_ENABLE_RTREE

capdb:	shell.c capdb.c
	$(CC) $(CFLAGS) $(COPTS) -o capdb shell.c capdb.c $(LIBS)
