/*
** 2023-07-21
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** This file is part of the JNI bindings for the capdb C API.
*/
package org.sqlite.jni.capi;

/**
   This enum contains all of the core and "extended" result codes used
   by the capdb library. It is provided not for use with the C-style
   API (with which it won't work) but for higher-level code which may
   find it useful to map SQLite result codes to human-readable names.
*/
public enum ResultCode {
  CAPDB_OK(CApi.CAPDB_OK),
  CAPDB_ERROR(CApi.CAPDB_ERROR),
  CAPDB_INTERNAL(CApi.CAPDB_INTERNAL),
  CAPDB_PERM(CApi.CAPDB_PERM),
  CAPDB_ABORT(CApi.CAPDB_ABORT),
  CAPDB_BUSY(CApi.CAPDB_BUSY),
  CAPDB_LOCKED(CApi.CAPDB_LOCKED),
  CAPDB_NOMEM(CApi.CAPDB_NOMEM),
  CAPDB_READONLY(CApi.CAPDB_READONLY),
  CAPDB_INTERRUPT(CApi.CAPDB_INTERRUPT),
  CAPDB_IOERR(CApi.CAPDB_IOERR),
  CAPDB_CORRUPT(CApi.CAPDB_CORRUPT),
  CAPDB_NOTFOUND(CApi.CAPDB_NOTFOUND),
  CAPDB_FULL(CApi.CAPDB_FULL),
  CAPDB_CANTOPEN(CApi.CAPDB_CANTOPEN),
  CAPDB_PROTOCOL(CApi.CAPDB_PROTOCOL),
  CAPDB_EMPTY(CApi.CAPDB_EMPTY),
  CAPDB_SCHEMA(CApi.CAPDB_SCHEMA),
  CAPDB_TOOBIG(CApi.CAPDB_TOOBIG),
  CAPDB_CONSTRAINT(CApi.CAPDB_CONSTRAINT),
  CAPDB_MISMATCH(CApi.CAPDB_MISMATCH),
  CAPDB_MISUSE(CApi.CAPDB_MISUSE),
  CAPDB_NOLFS(CApi.CAPDB_NOLFS),
  CAPDB_AUTH(CApi.CAPDB_AUTH),
  CAPDB_FORMAT(CApi.CAPDB_FORMAT),
  CAPDB_RANGE(CApi.CAPDB_RANGE),
  CAPDB_NOTADB(CApi.CAPDB_NOTADB),
  CAPDB_NOTICE(CApi.CAPDB_NOTICE),
  CAPDB_WARNING(CApi.CAPDB_WARNING),
  CAPDB_ROW(CApi.CAPDB_ROW),
  CAPDB_DONE(CApi.CAPDB_DONE),
  CAPDB_ERROR_MISSING_COLLSEQ(CApi.CAPDB_ERROR_MISSING_COLLSEQ),
  CAPDB_ERROR_RETRY(CApi.CAPDB_ERROR_RETRY),
  CAPDB_ERROR_SNAPSHOT(CApi.CAPDB_ERROR_SNAPSHOT),
  CAPDB_IOERR_READ(CApi.CAPDB_IOERR_READ),
  CAPDB_IOERR_SHORT_READ(CApi.CAPDB_IOERR_SHORT_READ),
  CAPDB_IOERR_WRITE(CApi.CAPDB_IOERR_WRITE),
  CAPDB_IOERR_FSYNC(CApi.CAPDB_IOERR_FSYNC),
  CAPDB_IOERR_DIR_FSYNC(CApi.CAPDB_IOERR_DIR_FSYNC),
  CAPDB_IOERR_TRUNCATE(CApi.CAPDB_IOERR_TRUNCATE),
  CAPDB_IOERR_FSTAT(CApi.CAPDB_IOERR_FSTAT),
  CAPDB_IOERR_UNLOCK(CApi.CAPDB_IOERR_UNLOCK),
  CAPDB_IOERR_RDLOCK(CApi.CAPDB_IOERR_RDLOCK),
  CAPDB_IOERR_DELETE(CApi.CAPDB_IOERR_DELETE),
  CAPDB_IOERR_BLOCKED(CApi.CAPDB_IOERR_BLOCKED),
  CAPDB_IOERR_NOMEM(CApi.CAPDB_IOERR_NOMEM),
  CAPDB_IOERR_ACCESS(CApi.CAPDB_IOERR_ACCESS),
  CAPDB_IOERR_CHECKRESERVEDLOCK(CApi.CAPDB_IOERR_CHECKRESERVEDLOCK),
  CAPDB_IOERR_LOCK(CApi.CAPDB_IOERR_LOCK),
  CAPDB_IOERR_CLOSE(CApi.CAPDB_IOERR_CLOSE),
  CAPDB_IOERR_DIR_CLOSE(CApi.CAPDB_IOERR_DIR_CLOSE),
  CAPDB_IOERR_SHMOPEN(CApi.CAPDB_IOERR_SHMOPEN),
  CAPDB_IOERR_SHMSIZE(CApi.CAPDB_IOERR_SHMSIZE),
  CAPDB_IOERR_SHMLOCK(CApi.CAPDB_IOERR_SHMLOCK),
  CAPDB_IOERR_SHMMAP(CApi.CAPDB_IOERR_SHMMAP),
  CAPDB_IOERR_SEEK(CApi.CAPDB_IOERR_SEEK),
  CAPDB_IOERR_DELETE_NOENT(CApi.CAPDB_IOERR_DELETE_NOENT),
  CAPDB_IOERR_MMAP(CApi.CAPDB_IOERR_MMAP),
  CAPDB_IOERR_GETTEMPPATH(CApi.CAPDB_IOERR_GETTEMPPATH),
  CAPDB_IOERR_CONVPATH(CApi.CAPDB_IOERR_CONVPATH),
  CAPDB_IOERR_VNODE(CApi.CAPDB_IOERR_VNODE),
  CAPDB_IOERR_AUTH(CApi.CAPDB_IOERR_AUTH),
  CAPDB_IOERR_BEGIN_ATOMIC(CApi.CAPDB_IOERR_BEGIN_ATOMIC),
  CAPDB_IOERR_COMMIT_ATOMIC(CApi.CAPDB_IOERR_COMMIT_ATOMIC),
  CAPDB_IOERR_ROLLBACK_ATOMIC(CApi.CAPDB_IOERR_ROLLBACK_ATOMIC),
  CAPDB_IOERR_DATA(CApi.CAPDB_IOERR_DATA),
  CAPDB_IOERR_CORRUPTFS(CApi.CAPDB_IOERR_CORRUPTFS),
  CAPDB_LOCKED_SHAREDCACHE(CApi.CAPDB_LOCKED_SHAREDCACHE),
  CAPDB_LOCKED_VTAB(CApi.CAPDB_LOCKED_VTAB),
  CAPDB_BUSY_RECOVERY(CApi.CAPDB_BUSY_RECOVERY),
  CAPDB_BUSY_SNAPSHOT(CApi.CAPDB_BUSY_SNAPSHOT),
  CAPDB_BUSY_TIMEOUT(CApi.CAPDB_BUSY_TIMEOUT),
  CAPDB_CANTOPEN_NOTEMPDIR(CApi.CAPDB_CANTOPEN_NOTEMPDIR),
  CAPDB_CANTOPEN_ISDIR(CApi.CAPDB_CANTOPEN_ISDIR),
  CAPDB_CANTOPEN_FULLPATH(CApi.CAPDB_CANTOPEN_FULLPATH),
  CAPDB_CANTOPEN_CONVPATH(CApi.CAPDB_CANTOPEN_CONVPATH),
  CAPDB_CANTOPEN_SYMLINK(CApi.CAPDB_CANTOPEN_SYMLINK),
  CAPDB_CORRUPT_VTAB(CApi.CAPDB_CORRUPT_VTAB),
  CAPDB_CORRUPT_SEQUENCE(CApi.CAPDB_CORRUPT_SEQUENCE),
  CAPDB_CORRUPT_INDEX(CApi.CAPDB_CORRUPT_INDEX),
  CAPDB_READONLY_RECOVERY(CApi.CAPDB_READONLY_RECOVERY),
  CAPDB_READONLY_CANTLOCK(CApi.CAPDB_READONLY_CANTLOCK),
  CAPDB_READONLY_ROLLBACK(CApi.CAPDB_READONLY_ROLLBACK),
  CAPDB_READONLY_DBMOVED(CApi.CAPDB_READONLY_DBMOVED),
  CAPDB_READONLY_CANTINIT(CApi.CAPDB_READONLY_CANTINIT),
  CAPDB_READONLY_DIRECTORY(CApi.CAPDB_READONLY_DIRECTORY),
  CAPDB_ABORT_ROLLBACK(CApi.CAPDB_ABORT_ROLLBACK),
  CAPDB_CONSTRAINT_CHECK(CApi.CAPDB_CONSTRAINT_CHECK),
  CAPDB_CONSTRAINT_COMMITHOOK(CApi.CAPDB_CONSTRAINT_COMMITHOOK),
  CAPDB_CONSTRAINT_FOREIGNKEY(CApi.CAPDB_CONSTRAINT_FOREIGNKEY),
  CAPDB_CONSTRAINT_FUNCTION(CApi.CAPDB_CONSTRAINT_FUNCTION),
  CAPDB_CONSTRAINT_NOTNULL(CApi.CAPDB_CONSTRAINT_NOTNULL),
  CAPDB_CONSTRAINT_PRIMARYKEY(CApi.CAPDB_CONSTRAINT_PRIMARYKEY),
  CAPDB_CONSTRAINT_TRIGGER(CApi.CAPDB_CONSTRAINT_TRIGGER),
  CAPDB_CONSTRAINT_UNIQUE(CApi.CAPDB_CONSTRAINT_UNIQUE),
  CAPDB_CONSTRAINT_VTAB(CApi.CAPDB_CONSTRAINT_VTAB),
  CAPDB_CONSTRAINT_ROWID(CApi.CAPDB_CONSTRAINT_ROWID),
  CAPDB_CONSTRAINT_PINNED(CApi.CAPDB_CONSTRAINT_PINNED),
  CAPDB_CONSTRAINT_DATATYPE(CApi.CAPDB_CONSTRAINT_DATATYPE),
  CAPDB_NOTICE_RECOVER_WAL(CApi.CAPDB_NOTICE_RECOVER_WAL),
  CAPDB_NOTICE_RECOVER_ROLLBACK(CApi.CAPDB_NOTICE_RECOVER_ROLLBACK),
  CAPDB_WARNING_AUTOINDEX(CApi.CAPDB_WARNING_AUTOINDEX),
  CAPDB_AUTH_USER(CApi.CAPDB_AUTH_USER),
  CAPDB_OK_LOAD_PERMANENTLY(CApi.CAPDB_OK_LOAD_PERMANENTLY);

  public final int value;

  ResultCode(int rc){
    value = rc;
    ResultCodeMap.set(rc, this);
  }

  /**
     Returns the entry from this enum for the given result code, or
     null if no match is found.
  */
  public static ResultCode getEntryForInt(int rc){
    return ResultCodeMap.get(rc);
  }

  /**
     Internal level of indirection required because we cannot initialize
     static enum members in an enum before the enum constructor is
     invoked.
  */
  private static final class ResultCodeMap {
    private static final java.util.Map<Integer,ResultCode> i2e
      = new java.util.HashMap<>();
    private static void set(int rc, ResultCode e){ i2e.put(rc, e); }
    private static ResultCode get(int rc){ return i2e.get(rc); }
  }

}
